main: cn.wode490390.nukkit.bounce.Bounce
name: "Bounce"
description: "Bounce plugin for Nukkit"
author: "wode490390"
website: "http://wode490390.cn/"
version: "${pom.version}"
api: ["1.0.0"]
load: POSTWORLD
permissions:
  bounce.use:
    description: Allows the player to bounce.
    default: true
